// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ometbnwcgrtkdmjnratx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tZXRibndjZ3J0a2Rtam5yYXR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzODUwNTUsImV4cCI6MjA2Mzk2MTA1NX0.hfUMXIRbz45403YKoqG2TXFDyzWyujII-FJgwcwiFS0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);